package objects.type;

public enum Type {
    INCOME_EARN,
    INCOME_PASSIVE,
    INCOME_PORTFOLIO,
    TAX_EARN,
    TAX_BUY,
    TAX_OWN,
    INVEST_STOCK,
    INVEST_REAL_ESTATE,
    INVEST_SAVING,
    INVEST_OTHER,
    HEALTH,
    COLLEGE_WORK,
    CAR_TRANSPORTATION,
    CAR_GAS,
    CAR_TOLL,
    GROCERY,
    RENT_MORTGAGE,
    UTILITY,
    PET,
    ENTERTAINMENT,
    MEAL,
    SHOP,
    CLOTHES,
    CHARITY
}
